apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.37.0
directories:
  - path: vendir/korifi
    contents:
      - path: .
        git:
          depth: 1
          url: https://github.com/cloudfoundry/korifi.git
          ref: v0.13.0
